# Generated by Django 2.2.6 on 2020-04-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_No', models.AutoField(help_text='Unique Emp no for Employee table', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Employee first name', max_length=14)),
                ('Last_Name', models.CharField(blank=True, help_text='Employee last name', max_length=14, null=True)),
                ('Birth_Date', models.DateField(blank=True, help_text='Employee birth date', null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Mobile_Number', models.PositiveIntegerField(default=0)),
                ('Email_Address', models.EmailField(max_length=80, unique=True)),
                ('Hire_Date', models.DateField(help_text='Employee joining date')),
                ('Emp_Type', models.CharField(choices=[('Exec', 'Executive'), ('Man', 'Manager')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('LeaveBal_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Leave_Type', models.CharField(choices=[('PL', 'Personal Leave'), ('AL', 'Annual Leave'), ('OT', 'Other')], max_length=10)),
                ('Available_Days', models.PositiveIntegerField(default=0, help_text='Remaining/available leave days per employee')),
                ('Allocated_Days', models.PositiveIntegerField(default=0, help_text='No of leave days allocated to a leave type per employee per year')),
                ('Exec_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExecLeaveRequest',
            fields=[
                ('ExecLeave_Req_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Leave_Type', models.CharField(choices=[('PL', 'Personal Leave'), ('AL', 'Annual Leave'), ('OT', 'Other')], max_length=30)),
                ('Begin_Date', models.DateField(help_text='Leave begin date')),
                ('End_Date', models.DateField(help_text='Leave end date')),
                ('Requested_Days', models.PositiveIntegerField(default=0, help_text='Total no of requested leave days')),
                ('Leave_Status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('DL', 'Declined'), ('CA', 'Cancelled')], max_length=10)),
                ('Exec_Comments', models.CharField(max_length=500, null=True)),
                ('Exec_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Exec_ID', to='emp.Employee')),
                ('Man_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Manager_Emp_No', to='emp.Employee')),
            ],
        ),
    ]
